import Link from "next/link";
import type { ReactNode } from "react";

const legalEmail = process.env.NEXT_PUBLIC_LEGAL_CONTACT_EMAIL ?? "PENDIENTE_DE_CONFIGURAR";
const legalEntity = process.env.NEXT_PUBLIC_LEGAL_ENTITY_NAME ?? "Mercadia / next.io by Mercadia";
const lastUpdated = "14 de agosto de 2026";

function LegalShell({ title, children }: { title: string; children: ReactNode }) {
  return <main className="legal-page"><header className="legal-header"><Link href="/" className="brand"><span className="brand-mark">n</span><span>next.io <span>by Mercadia</span></span></Link><nav><Link href="/terminos">Terminos</Link><Link href="/privacidad">Privacidad</Link><Link href="/eliminacion-de-datos">Datos</Link></nav></header><article className="legal-document"><p className="eyebrow">INFORMACION LEGAL</p><h1>{title}</h1><p className="legal-updated">Ultima actualizacion: {lastUpdated}</p>{children}</article><footer className="legal-footer"><Link href="/">Volver a inicio</Link><span>next.io by Mercadia</span></footer></main>;
}

export function TermsDocument() {
  return <LegalShell title="Terminos y condiciones"><section><h2>1. Alcance del servicio</h2><p>next.io by Mercadia es una plataforma SaaS para centralizar la atencion por canales digitales, administrar conocimiento del negocio y generar asistencia mediante inteligencia artificial. El servicio se contrata por organizacion y conforme al plan, limites, precios e impuestos que se muestren antes del pago.</p></section><section><h2>2. Cuenta, planes y pagos</h2><p>La persona que registra una organizacion declara contar con facultades para hacerlo. Micro se activa solo despues de un pago confirmado. En los planes que muestren la opcion, la prueba gratuita es opcional; al concluir, o al exceder sus limites, se requerira contratar un plan activo para continuar usando funciones sujetas a suscripcion.</p><p>Los cargos recurrentes, cancelaciones y actualizaciones de tarjeta se procesan por Stripe. Cada cliente debe mantener datos de facturacion correctos y revisar el precio, periodo y limites antes de confirmar Checkout.</p></section><section><h2>3. Canales Meta y WhatsApp Business</h2><p>Las conexiones con Instagram, Facebook y WhatsApp Business requieren que el cliente sea titular o administrador autorizado de las cuentas correspondientes y acepte las condiciones de Meta. La disponibilidad depende de la aprobacion, politicas, permisos, plantillas, ventanas de conversacion y tarifas que Meta aplique a cada cuenta.</p><p>El cliente es responsable de obtener los consentimientos y avisos necesarios para comunicarse con sus propios contactos, de respetar bajas y de no usar la plataforma para spam, fraude, contenido ilegal o tratamiento no autorizado de datos personales.</p></section><section><h2>4. IA y contenido del cliente</h2><p>El cliente conserva la responsabilidad por la exactitud del conocimiento, ofertas, horarios, politicas y respuestas que configure. La IA puede producir sugerencias; antes de automatizar mensajes el cliente debe revisar sus instrucciones, reglas de transferencia a humano y datos comerciales. No debe usarse para decisiones exclusivamente automatizadas con efectos juridicos relevantes sobre personas.</p></section><section><h2>5. Uso aceptable, suspension y responsabilidad</h2><p>Podremos restringir el servicio ante incumplimiento legal, riesgo de seguridad, falta de pago, instrucciones de una autoridad o violacion de estos terminos. En la medida permitida por la ley, el servicio se presta sobre una base de disponibilidad razonable; no sustituye revisiones humanas, asesoramiento legal, medico, financiero ni profesional especializado.</p></section><section><h2>6. Cambios y contacto</h2><p>Podremos actualizar estos terminos para reflejar cambios del servicio o normativos. Los cambios materiales se comunicaran por medios razonables. Para asuntos legales o del servicio, el responsable designado es {legalEntity}. Contacto: {legalEmail}.</p></section></LegalShell>;
}

export function PrivacyDocument() {
  return <LegalShell title="Aviso de privacidad"><section><h2>1. Responsable y contacto</h2><p>El responsable del tratamiento de los datos de la plataforma es {legalEntity}. Para privacidad, solicitudes ARCO, revocacion del consentimiento o preguntas sobre este aviso: {legalEmail}.</p><p className="legal-alert">Antes de publicar este aviso debes configurar en Vercel el nombre o razon social y el correo legal reales. No publiques con el valor PENDIENTE_DE_CONFIGURAR.</p></section><section><h2>2. Datos y finalidades</h2><p>Podemos tratar datos de cuenta y acceso, datos de facturacion, datos tecnicos y de seguridad, configuracion de la organizacion, y el contenido que el cliente cargue o reciba mediante canales conectados. Las finalidades primarias son prestar el servicio, autenticar usuarios, administrar pagos, limitar consumo, prevenir fraude, dar soporte, mantener seguridad y cumplir obligaciones legales.</p><p>Las comunicaciones comerciales propias se enviaran solo cuando exista una base legal aplicable y se podran desactivar por los medios habilitados. No vendemos datos personales.</p></section><section><h2>3. Rol de cada negocio</h2><p>Respecto de los contactos, conversaciones y datos de clientes que cada organizacion sube o recibe en la plataforma, esa organizacion es responsable del tratamiento y next.io actua como encargado o proveedor tecnologico, conforme a sus instrucciones y al contrato aplicable. Cada organizacion debe contar con su propio aviso de privacidad y bases de tratamiento.</p></section><section><h2>4. Proveedores y transferencias</h2><p>Para operar el servicio se pueden utilizar proveedores de alojamiento, base de datos, procesamiento de pagos, canales Meta y proveedores de IA, estrictamente en la medida necesaria para prestar el servicio, seguridad, soporte y cumplimiento. Cualquier transferencia se realizara conforme a la ley aplicable, contratos y medidas de seguridad correspondientes.</p></section><section><h2>5. Derechos ARCO</h2><p>Las personas titulares pueden solicitar Acceso, Rectificacion, Cancelacion u Oposicion respecto de sus datos personales. La solicitud debe indicar nombre, medio para recibir respuesta, derecho que se desea ejercer y la informacion que facilite localizar los datos; podremos pedir informacion razonable para verificar identidad y representacion. Atenderemos solicitudes en los plazos previstos por la legislacion mexicana aplicable.</p></section><section><h2>6. Seguridad, conservacion y cambios</h2><p>Aplicamos medidas administrativas, tecnicas y fisicas razonables, incluyendo controles de acceso y proteccion de credenciales. Conservamos los datos durante la relacion de servicio y el tiempo necesario para fines legales, de seguridad, facturacion o defensa de derechos. Este aviso puede cambiar; publicaremos la version vigente en esta pagina.</p></section></LegalShell>;
}

export function DataDeletionDocument() {
  return <LegalShell title="Eliminacion de datos"><section><h2>Solicita eliminacion o cancelacion</h2><p>Para solicitar eliminacion de una cuenta de next.io by Mercadia, escribe a {legalEmail} con el asunto <strong>Eliminacion de datos</strong>. Indica el correo de la cuenta, nombre de la organizacion y el alcance de tu solicitud. Te pediremos una verificacion razonable de identidad antes de procesarla.</p></section><section><h2>Datos de contactos de un negocio</h2><p>Si conversaste con una empresa usuaria de la plataforma, dicha empresa es normalmente responsable de tus datos y debe atender primero tu solicitud. Tambien puedes escribirnos para canalizarla y verificar el tratamiento correspondiente.</p></section><section><h2>Meta, Instagram y WhatsApp</h2><p>La eliminacion de datos asociados a conexiones de Meta se atendera conforme a la solicitud de la persona titular, las obligaciones legales de conservacion y los requisitos tecnicos de Meta. Desconectar un canal no elimina automaticamente registros que deban conservarse por seguridad, facturacion o cumplimiento; esos registros se suprimiran o anonimizaran cuando proceda.</p></section></LegalShell>;
}
